require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnunciosController do

  # This should return the minimal set of attributes required to create a valid
  # Anuncio. As you add validations to Anuncio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "link" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnunciosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all anuncios as @anuncios" do
      anuncio = Anuncio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:anuncios).should eq([anuncio])
    end
  end

  describe "GET show" do
    it "assigns the requested anuncio as @anuncio" do
      anuncio = Anuncio.create! valid_attributes
      get :show, {:id => anuncio.to_param}, valid_session
      assigns(:anuncio).should eq(anuncio)
    end
  end

  describe "GET new" do
    it "assigns a new anuncio as @anuncio" do
      get :new, {}, valid_session
      assigns(:anuncio).should be_a_new(Anuncio)
    end
  end

  describe "GET edit" do
    it "assigns the requested anuncio as @anuncio" do
      anuncio = Anuncio.create! valid_attributes
      get :edit, {:id => anuncio.to_param}, valid_session
      assigns(:anuncio).should eq(anuncio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Anuncio" do
        expect {
          post :create, {:anuncio => valid_attributes}, valid_session
        }.to change(Anuncio, :count).by(1)
      end

      it "assigns a newly created anuncio as @anuncio" do
        post :create, {:anuncio => valid_attributes}, valid_session
        assigns(:anuncio).should be_a(Anuncio)
        assigns(:anuncio).should be_persisted
      end

      it "redirects to the created anuncio" do
        post :create, {:anuncio => valid_attributes}, valid_session
        response.should redirect_to(Anuncio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved anuncio as @anuncio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Anuncio.any_instance.stub(:save).and_return(false)
        post :create, {:anuncio => { "link" => "invalid value" }}, valid_session
        assigns(:anuncio).should be_a_new(Anuncio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Anuncio.any_instance.stub(:save).and_return(false)
        post :create, {:anuncio => { "link" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested anuncio" do
        anuncio = Anuncio.create! valid_attributes
        # Assuming there are no other anuncios in the database, this
        # specifies that the Anuncio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Anuncio.any_instance.should_receive(:update_attributes).with({ "link" => "MyString" })
        put :update, {:id => anuncio.to_param, :anuncio => { "link" => "MyString" }}, valid_session
      end

      it "assigns the requested anuncio as @anuncio" do
        anuncio = Anuncio.create! valid_attributes
        put :update, {:id => anuncio.to_param, :anuncio => valid_attributes}, valid_session
        assigns(:anuncio).should eq(anuncio)
      end

      it "redirects to the anuncio" do
        anuncio = Anuncio.create! valid_attributes
        put :update, {:id => anuncio.to_param, :anuncio => valid_attributes}, valid_session
        response.should redirect_to(anuncio)
      end
    end

    describe "with invalid params" do
      it "assigns the anuncio as @anuncio" do
        anuncio = Anuncio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Anuncio.any_instance.stub(:save).and_return(false)
        put :update, {:id => anuncio.to_param, :anuncio => { "link" => "invalid value" }}, valid_session
        assigns(:anuncio).should eq(anuncio)
      end

      it "re-renders the 'edit' template" do
        anuncio = Anuncio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Anuncio.any_instance.stub(:save).and_return(false)
        put :update, {:id => anuncio.to_param, :anuncio => { "link" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested anuncio" do
      anuncio = Anuncio.create! valid_attributes
      expect {
        delete :destroy, {:id => anuncio.to_param}, valid_session
      }.to change(Anuncio, :count).by(-1)
    end

    it "redirects to the anuncios list" do
      anuncio = Anuncio.create! valid_attributes
      delete :destroy, {:id => anuncio.to_param}, valid_session
      response.should redirect_to(anuncios_url)
    end
  end

end
