require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CiudadesController do

  # This should return the minimal set of attributes required to create a valid
  # Ciudad. As you add validations to Ciudad, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CiudadesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ciudades as @ciudades" do
      ciudad = Ciudad.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ciudades).should eq([ciudad])
    end
  end

  describe "GET show" do
    it "assigns the requested ciudad as @ciudad" do
      ciudad = Ciudad.create! valid_attributes
      get :show, {:id => ciudad.to_param}, valid_session
      assigns(:ciudad).should eq(ciudad)
    end
  end

  describe "GET new" do
    it "assigns a new ciudad as @ciudad" do
      get :new, {}, valid_session
      assigns(:ciudad).should be_a_new(Ciudad)
    end
  end

  describe "GET edit" do
    it "assigns the requested ciudad as @ciudad" do
      ciudad = Ciudad.create! valid_attributes
      get :edit, {:id => ciudad.to_param}, valid_session
      assigns(:ciudad).should eq(ciudad)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Ciudad" do
        expect {
          post :create, {:ciudad => valid_attributes}, valid_session
        }.to change(Ciudad, :count).by(1)
      end

      it "assigns a newly created ciudad as @ciudad" do
        post :create, {:ciudad => valid_attributes}, valid_session
        assigns(:ciudad).should be_a(Ciudad)
        assigns(:ciudad).should be_persisted
      end

      it "redirects to the created ciudad" do
        post :create, {:ciudad => valid_attributes}, valid_session
        response.should redirect_to(Ciudad.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ciudad as @ciudad" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ciudad.any_instance.stub(:save).and_return(false)
        post :create, {:ciudad => { "nombre" => "invalid value" }}, valid_session
        assigns(:ciudad).should be_a_new(Ciudad)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Ciudad.any_instance.stub(:save).and_return(false)
        post :create, {:ciudad => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ciudad" do
        ciudad = Ciudad.create! valid_attributes
        # Assuming there are no other ciudades in the database, this
        # specifies that the Ciudad created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Ciudad.any_instance.should_receive(:update_attributes).with({ "nombre" => "MyString" })
        put :update, {:id => ciudad.to_param, :ciudad => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested ciudad as @ciudad" do
        ciudad = Ciudad.create! valid_attributes
        put :update, {:id => ciudad.to_param, :ciudad => valid_attributes}, valid_session
        assigns(:ciudad).should eq(ciudad)
      end

      it "redirects to the ciudad" do
        ciudad = Ciudad.create! valid_attributes
        put :update, {:id => ciudad.to_param, :ciudad => valid_attributes}, valid_session
        response.should redirect_to(ciudad)
      end
    end

    describe "with invalid params" do
      it "assigns the ciudad as @ciudad" do
        ciudad = Ciudad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ciudad.any_instance.stub(:save).and_return(false)
        put :update, {:id => ciudad.to_param, :ciudad => { "nombre" => "invalid value" }}, valid_session
        assigns(:ciudad).should eq(ciudad)
      end

      it "re-renders the 'edit' template" do
        ciudad = Ciudad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Ciudad.any_instance.stub(:save).and_return(false)
        put :update, {:id => ciudad.to_param, :ciudad => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ciudad" do
      ciudad = Ciudad.create! valid_attributes
      expect {
        delete :destroy, {:id => ciudad.to_param}, valid_session
      }.to change(Ciudad, :count).by(-1)
    end

    it "redirects to the ciudades list" do
      ciudad = Ciudad.create! valid_attributes
      delete :destroy, {:id => ciudad.to_param}, valid_session
      response.should redirect_to(ciudades_url)
    end
  end

end
