require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DireccionesController do

  # This should return the minimal set of attributes required to create a valid
  # Direccion. As you add validations to Direccion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "provincia" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DireccionesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all direcciones as @direcciones" do
      direccion = Direccion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:direcciones).should eq([direccion])
    end
  end

  describe "GET show" do
    it "assigns the requested direccion as @direccion" do
      direccion = Direccion.create! valid_attributes
      get :show, {:id => direccion.to_param}, valid_session
      assigns(:direccion).should eq(direccion)
    end
  end

  describe "GET new" do
    it "assigns a new direccion as @direccion" do
      get :new, {}, valid_session
      assigns(:direccion).should be_a_new(Direccion)
    end
  end

  describe "GET edit" do
    it "assigns the requested direccion as @direccion" do
      direccion = Direccion.create! valid_attributes
      get :edit, {:id => direccion.to_param}, valid_session
      assigns(:direccion).should eq(direccion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Direccion" do
        expect {
          post :create, {:direccion => valid_attributes}, valid_session
        }.to change(Direccion, :count).by(1)
      end

      it "assigns a newly created direccion as @direccion" do
        post :create, {:direccion => valid_attributes}, valid_session
        assigns(:direccion).should be_a(Direccion)
        assigns(:direccion).should be_persisted
      end

      it "redirects to the created direccion" do
        post :create, {:direccion => valid_attributes}, valid_session
        response.should redirect_to(Direccion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved direccion as @direccion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Direccion.any_instance.stub(:save).and_return(false)
        post :create, {:direccion => { "provincia" => "invalid value" }}, valid_session
        assigns(:direccion).should be_a_new(Direccion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Direccion.any_instance.stub(:save).and_return(false)
        post :create, {:direccion => { "provincia" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested direccion" do
        direccion = Direccion.create! valid_attributes
        # Assuming there are no other direcciones in the database, this
        # specifies that the Direccion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Direccion.any_instance.should_receive(:update_attributes).with({ "provincia" => "MyString" })
        put :update, {:id => direccion.to_param, :direccion => { "provincia" => "MyString" }}, valid_session
      end

      it "assigns the requested direccion as @direccion" do
        direccion = Direccion.create! valid_attributes
        put :update, {:id => direccion.to_param, :direccion => valid_attributes}, valid_session
        assigns(:direccion).should eq(direccion)
      end

      it "redirects to the direccion" do
        direccion = Direccion.create! valid_attributes
        put :update, {:id => direccion.to_param, :direccion => valid_attributes}, valid_session
        response.should redirect_to(direccion)
      end
    end

    describe "with invalid params" do
      it "assigns the direccion as @direccion" do
        direccion = Direccion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Direccion.any_instance.stub(:save).and_return(false)
        put :update, {:id => direccion.to_param, :direccion => { "provincia" => "invalid value" }}, valid_session
        assigns(:direccion).should eq(direccion)
      end

      it "re-renders the 'edit' template" do
        direccion = Direccion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Direccion.any_instance.stub(:save).and_return(false)
        put :update, {:id => direccion.to_param, :direccion => { "provincia" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested direccion" do
      direccion = Direccion.create! valid_attributes
      expect {
        delete :destroy, {:id => direccion.to_param}, valid_session
      }.to change(Direccion, :count).by(-1)
    end

    it "redirects to the direcciones list" do
      direccion = Direccion.create! valid_attributes
      delete :destroy, {:id => direccion.to_param}, valid_session
      response.should redirect_to(direcciones_url)
    end
  end

end
