require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PortadasController do

  # This should return the minimal set of attributes required to create a valid
  # Portada. As you add validations to Portada, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "imagen" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PortadasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all portadas as @portadas" do
      portada = Portada.create! valid_attributes
      get :index, {}, valid_session
      assigns(:portadas).should eq([portada])
    end
  end

  describe "GET show" do
    it "assigns the requested portada as @portada" do
      portada = Portada.create! valid_attributes
      get :show, {:id => portada.to_param}, valid_session
      assigns(:portada).should eq(portada)
    end
  end

  describe "GET new" do
    it "assigns a new portada as @portada" do
      get :new, {}, valid_session
      assigns(:portada).should be_a_new(Portada)
    end
  end

  describe "GET edit" do
    it "assigns the requested portada as @portada" do
      portada = Portada.create! valid_attributes
      get :edit, {:id => portada.to_param}, valid_session
      assigns(:portada).should eq(portada)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Portada" do
        expect {
          post :create, {:portada => valid_attributes}, valid_session
        }.to change(Portada, :count).by(1)
      end

      it "assigns a newly created portada as @portada" do
        post :create, {:portada => valid_attributes}, valid_session
        assigns(:portada).should be_a(Portada)
        assigns(:portada).should be_persisted
      end

      it "redirects to the created portada" do
        post :create, {:portada => valid_attributes}, valid_session
        response.should redirect_to(Portada.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved portada as @portada" do
        # Trigger the behavior that occurs when invalid params are submitted
        Portada.any_instance.stub(:save).and_return(false)
        post :create, {:portada => { "imagen" => "invalid value" }}, valid_session
        assigns(:portada).should be_a_new(Portada)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Portada.any_instance.stub(:save).and_return(false)
        post :create, {:portada => { "imagen" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested portada" do
        portada = Portada.create! valid_attributes
        # Assuming there are no other portadas in the database, this
        # specifies that the Portada created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Portada.any_instance.should_receive(:update_attributes).with({ "imagen" => "MyString" })
        put :update, {:id => portada.to_param, :portada => { "imagen" => "MyString" }}, valid_session
      end

      it "assigns the requested portada as @portada" do
        portada = Portada.create! valid_attributes
        put :update, {:id => portada.to_param, :portada => valid_attributes}, valid_session
        assigns(:portada).should eq(portada)
      end

      it "redirects to the portada" do
        portada = Portada.create! valid_attributes
        put :update, {:id => portada.to_param, :portada => valid_attributes}, valid_session
        response.should redirect_to(portada)
      end
    end

    describe "with invalid params" do
      it "assigns the portada as @portada" do
        portada = Portada.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Portada.any_instance.stub(:save).and_return(false)
        put :update, {:id => portada.to_param, :portada => { "imagen" => "invalid value" }}, valid_session
        assigns(:portada).should eq(portada)
      end

      it "re-renders the 'edit' template" do
        portada = Portada.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Portada.any_instance.stub(:save).and_return(false)
        put :update, {:id => portada.to_param, :portada => { "imagen" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested portada" do
      portada = Portada.create! valid_attributes
      expect {
        delete :destroy, {:id => portada.to_param}, valid_session
      }.to change(Portada, :count).by(-1)
    end

    it "redirects to the portadas list" do
      portada = Portada.create! valid_attributes
      delete :destroy, {:id => portada.to_param}, valid_session
      response.should redirect_to(portadas_url)
    end
  end

end
