require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProvinciasController do

  # This should return the minimal set of attributes required to create a valid
  # Provincia. As you add validations to Provincia, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProvinciasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all provincias as @provincias" do
      provincia = Provincia.create! valid_attributes
      get :index, {}, valid_session
      assigns(:provincias).should eq([provincia])
    end
  end

  describe "GET show" do
    it "assigns the requested provincia as @provincia" do
      provincia = Provincia.create! valid_attributes
      get :show, {:id => provincia.to_param}, valid_session
      assigns(:provincia).should eq(provincia)
    end
  end

  describe "GET new" do
    it "assigns a new provincia as @provincia" do
      get :new, {}, valid_session
      assigns(:provincia).should be_a_new(Provincia)
    end
  end

  describe "GET edit" do
    it "assigns the requested provincia as @provincia" do
      provincia = Provincia.create! valid_attributes
      get :edit, {:id => provincia.to_param}, valid_session
      assigns(:provincia).should eq(provincia)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Provincia" do
        expect {
          post :create, {:provincia => valid_attributes}, valid_session
        }.to change(Provincia, :count).by(1)
      end

      it "assigns a newly created provincia as @provincia" do
        post :create, {:provincia => valid_attributes}, valid_session
        assigns(:provincia).should be_a(Provincia)
        assigns(:provincia).should be_persisted
      end

      it "redirects to the created provincia" do
        post :create, {:provincia => valid_attributes}, valid_session
        response.should redirect_to(Provincia.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved provincia as @provincia" do
        # Trigger the behavior that occurs when invalid params are submitted
        Provincia.any_instance.stub(:save).and_return(false)
        post :create, {:provincia => { "nombre" => "invalid value" }}, valid_session
        assigns(:provincia).should be_a_new(Provincia)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Provincia.any_instance.stub(:save).and_return(false)
        post :create, {:provincia => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested provincia" do
        provincia = Provincia.create! valid_attributes
        # Assuming there are no other provincias in the database, this
        # specifies that the Provincia created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Provincia.any_instance.should_receive(:update_attributes).with({ "nombre" => "MyString" })
        put :update, {:id => provincia.to_param, :provincia => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested provincia as @provincia" do
        provincia = Provincia.create! valid_attributes
        put :update, {:id => provincia.to_param, :provincia => valid_attributes}, valid_session
        assigns(:provincia).should eq(provincia)
      end

      it "redirects to the provincia" do
        provincia = Provincia.create! valid_attributes
        put :update, {:id => provincia.to_param, :provincia => valid_attributes}, valid_session
        response.should redirect_to(provincia)
      end
    end

    describe "with invalid params" do
      it "assigns the provincia as @provincia" do
        provincia = Provincia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Provincia.any_instance.stub(:save).and_return(false)
        put :update, {:id => provincia.to_param, :provincia => { "nombre" => "invalid value" }}, valid_session
        assigns(:provincia).should eq(provincia)
      end

      it "re-renders the 'edit' template" do
        provincia = Provincia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Provincia.any_instance.stub(:save).and_return(false)
        put :update, {:id => provincia.to_param, :provincia => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested provincia" do
      provincia = Provincia.create! valid_attributes
      expect {
        delete :destroy, {:id => provincia.to_param}, valid_session
      }.to change(Provincia, :count).by(-1)
    end

    it "redirects to the provincias list" do
      provincia = Provincia.create! valid_attributes
      delete :destroy, {:id => provincia.to_param}, valid_session
      response.should redirect_to(provincias_url)
    end
  end

end
