require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PublicacionesController do

  # This should return the minimal set of attributes required to create a valid
  # Publicacion. As you add validations to Publicacion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tipo" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PublicacionesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all publicaciones as @publicaciones" do
      publicacion = Publicacion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:publicaciones).should eq([publicacion])
    end
  end

  describe "GET show" do
    it "assigns the requested publicacion as @publicacion" do
      publicacion = Publicacion.create! valid_attributes
      get :show, {:id => publicacion.to_param}, valid_session
      assigns(:publicacion).should eq(publicacion)
    end
  end

  describe "GET new" do
    it "assigns a new publicacion as @publicacion" do
      get :new, {}, valid_session
      assigns(:publicacion).should be_a_new(Publicacion)
    end
  end

  describe "GET edit" do
    it "assigns the requested publicacion as @publicacion" do
      publicacion = Publicacion.create! valid_attributes
      get :edit, {:id => publicacion.to_param}, valid_session
      assigns(:publicacion).should eq(publicacion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Publicacion" do
        expect {
          post :create, {:publicacion => valid_attributes}, valid_session
        }.to change(Publicacion, :count).by(1)
      end

      it "assigns a newly created publicacion as @publicacion" do
        post :create, {:publicacion => valid_attributes}, valid_session
        assigns(:publicacion).should be_a(Publicacion)
        assigns(:publicacion).should be_persisted
      end

      it "redirects to the created publicacion" do
        post :create, {:publicacion => valid_attributes}, valid_session
        response.should redirect_to(Publicacion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved publicacion as @publicacion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Publicacion.any_instance.stub(:save).and_return(false)
        post :create, {:publicacion => { "tipo" => "invalid value" }}, valid_session
        assigns(:publicacion).should be_a_new(Publicacion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Publicacion.any_instance.stub(:save).and_return(false)
        post :create, {:publicacion => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested publicacion" do
        publicacion = Publicacion.create! valid_attributes
        # Assuming there are no other publicaciones in the database, this
        # specifies that the Publicacion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Publicacion.any_instance.should_receive(:update_attributes).with({ "tipo" => "MyString" })
        put :update, {:id => publicacion.to_param, :publicacion => { "tipo" => "MyString" }}, valid_session
      end

      it "assigns the requested publicacion as @publicacion" do
        publicacion = Publicacion.create! valid_attributes
        put :update, {:id => publicacion.to_param, :publicacion => valid_attributes}, valid_session
        assigns(:publicacion).should eq(publicacion)
      end

      it "redirects to the publicacion" do
        publicacion = Publicacion.create! valid_attributes
        put :update, {:id => publicacion.to_param, :publicacion => valid_attributes}, valid_session
        response.should redirect_to(publicacion)
      end
    end

    describe "with invalid params" do
      it "assigns the publicacion as @publicacion" do
        publicacion = Publicacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Publicacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => publicacion.to_param, :publicacion => { "tipo" => "invalid value" }}, valid_session
        assigns(:publicacion).should eq(publicacion)
      end

      it "re-renders the 'edit' template" do
        publicacion = Publicacion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Publicacion.any_instance.stub(:save).and_return(false)
        put :update, {:id => publicacion.to_param, :publicacion => { "tipo" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested publicacion" do
      publicacion = Publicacion.create! valid_attributes
      expect {
        delete :destroy, {:id => publicacion.to_param}, valid_session
      }.to change(Publicacion, :count).by(-1)
    end

    it "redirects to the publicaciones list" do
      publicacion = Publicacion.create! valid_attributes
      delete :destroy, {:id => publicacion.to_param}, valid_session
      response.should redirect_to(publicaciones_url)
    end
  end

end
